# S0-Proyecto

DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd;

USE bd;


CREATE TABLE JUGADORES ( 
   ID INT NOT NULL,
   usuario VARCHAR(20),
   contraseña VARCHAR(20),
   PRIMARY KEY (ID)

)ENGINE=innoDB;


CREATE TABLE PARTIDAS ( 
   ID INT NOT NULL,
   tablon VARCHAR(20),
   ganador VARCHAR(20),
   numjugadores INT,
   PRIMARY KEY (ID)

)ENGINE=innoDB;


CREATE TABLE RELACION ( 
   ID_P INT NOT NULL,
   ID_J INT NOT NULL,
   FOREIGN KEY (ID_P) REFERENCES PARTIDAS(ID),
   FOREIGN KEY (ID_J) REFERENCES JUGADORES(ID)

)ENGINE=innoDB;



INSERT INTO JUGADORES VALUES ( 1, 'marialcp','mlcp90');
INSERT INTO JUGADORES VALUES ( 2, 'manelhs','cbc89');
INSERT INTO JUGADORES VALUES ( 3, 'jorge99c','blue9982');
INSERT INTO JUGADORES VALUES ( 4, 'lourdes78','lp849');
INSERT INTO JUGADORES VALUES ( 5, 'sanchez89','greenlko');
INSERT INTO JUGADORES VALUES ( 6, 'marcvp99','cvp980');

INSERT INTO PARTIDAS VALUES ( 1, 'HarryPotter','manelhs',4);
INSERT INTO PARTIDAS VALUES ( 2, 'LaCasaDePapel','sanchez89',2);
INSERT INTO PARTIDAS VALUES ( 3, 'StarWars','lourdes78',2);

INSERT INTO RELACION VALUES ( 2,1);
INSERT INTO RELACION VALUES ( 3,1);
INSERT INTO RELACION VALUES ( 1,2);
INSERT INTO RELACION VALUES ( 1,3);
INSERT INTO RELACION VALUES ( 1,6);
INSERT INTO RELACION VALUES ( 1,5);
INSERT INTO RELACION VALUES ( 2,5);
INSERT INTO RELACION VALUES ( 3,4);
